spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:h2:file:./tiny-url-test-db

  liquibase:
    change-log: db/dbchangelog-test.yaml

  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8181