spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:h2:file:./tiny-url-test-db
    username: sa
    password:

  liquibase:
    change-log: db/dbchangelog-test.yaml
    contexts: test

  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8181

tiny:
  amount-of-popular-urls:
    offset: 0
    limit: 3
